theme = "papermod"
relativeURLs = true
baseURL = "/"
title = "Florijns Blog"
author = "Florijn Munster"
paginate = 4
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
math = true

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
[params.assets]
  disableFingerprinting = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags" 
    weight = 2
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 3
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]